subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/wwc2/acc_signal/
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/wwc2/wwc_gpio_ctrl/
obj-y += acc_signal.o
obj-y += acc_signal_drv.o


