subdir-ccflags-y += -Werror -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
subdir-ccflags-y += -Werror -I$(srctree)/drivers/input/touchscreen/mediatek/
subdir-ccflags-y += -Werror -I$$(srctree)/drivers/input/touchscreen/mediatek/wwc2_virtual_touch/

obj-$(CONFIG_WWC2_VIRTUAL_TOUCH_SUPPORT) += wwc2_virtual_touch.o
obj-$(CONFIG_WWC2_VIRTUAL_TOUCH_BOARD_SUPPORT) += wwc2_touch_board.o

