subdir-ccflags-y +=  -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
subdir-ccflags-y +=  -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/mach/
subdir-ccflags-y +=  -I$(srctree)/drivers/misc/mediatek/wwc2/wwc_gpio_ctrl/

obj-y += wwc_gpio_ctrl.o
